<template>
    <div class="list cards-list">
        <ul>
            <bro-good-list-item v-for="item in items" :key="item.id" :initItem="item"></bro-good-list-item>
        </ul>
    </div>
</template>
<script>
import broGoodListItem from './bro_good_list_item';
export default {
    components: {
        'bro-good-list-item': broGoodListItem
    },
    data: function(){
        return {
            items: [],
            offset: 0,
            limit: 100
        }
    },
    methods: {
        getGoodList: function(){
            var self = this;
            /*this.$request.json('/api/pwa/goods', { limit:this.limit, offset:this.offset }, function (data) {
                self.items = data;
            }, function(data){
                console.log('error', data)
            });*/
            this.items = [{
                "id": 8410,
                "iblock_id": 13,
                "name": "Стиральный порошок Bio-White для белья с экстрактом хлопка, Bio-Mio, 1,5кг",
                "infoves": "Вес 1шт. - 1,5кг",
                "quantity": 0,
                "weight": 1500,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 490,
                "discount": 0,
                "discount_price": 490,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 8411,
                "iblock_id": 13,
                "name": "Варенье из чеснока с апельсином, Любимая сладость, 320г",
                "infoves": "Вес 1 шт. - 320г",
                "quantity": 0,
                "weight": 320,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 250,
                "discount": 0,
                "discount_price": 250,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 8412,
                "iblock_id": 13,
                "name": "Варенье из грейпфрута с апельсином, Любимая сладость, 320г",
                "infoves": "Вес 1 шт. - 320г",
                "quantity": 0,
                "weight": 320,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 250,
                "discount": 0,
                "discount_price": 250,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 8413,
                "iblock_id": 13,
                "name": "Перец Черный, Kotanyi, 36г",
                "infoves": "Вес 1шт. - 36г",
                "quantity": 0,
                "weight": 36,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 222,
                "discount": 0,
                "discount_price": 222,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 0,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 6680,
                "iblock_id": 13,
                "name": "Яйца куриные СО, Лето, лоток 10шт.",
                "infoves": "В 1 упаковке -10шт.",
                "quantity": 0,
                "weight": 750,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 89,
                "discount": 0,
                "discount_price": 89,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 754,
                "iblock_id": 13,
                "name": "Авокадо стандарт",
                "infoves": "Вес 1 шт. ~ 200г",
                "quantity": 12,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 54,
                "discount": 0,
                "discount_price": 54,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 6540,
                "iblock_id": 13,
                "name": "Круассан 4U с какао и кремом ваниль, 90г",
                "infoves": "Вес 1 уп. - 90г",
                "quantity": 23,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/098\/10_10_0\/098999ac2313bee99f99cd136cf7c9a7.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/098\/300_300_0\/098999ac2313bee99f99cd136cf7c9a7.jpg",
                "currency": "RUB",
                "price": 59,
                "discount": 0,
                "discount_price": 59,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 6535,
                "iblock_id": 13,
                "name": "Круассан 4U с кремом какао, 50г",
                "infoves": "Вес 1 уп. - 50г",
                "quantity": 19,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/d81\/10_10_0\/d81cfb29c95d42b11113f8e5888f74ed.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/d81\/300_300_0\/d81cfb29c95d42b11113f8e5888f74ed.jpg",
                "currency": "RUB",
                "price": 47,
                "discount": 0,
                "discount_price": 47,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 6538,
                "iblock_id": 13,
                "name": "Круассан 4U с абрикосовым джемом, 50г",
                "infoves": "Вес 1 уп. - 50г",
                "quantity": -1,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/129\/10_10_0\/129a957b5aeabdabe58a1ba1c70d3317.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/129\/300_300_0\/129a957b5aeabdabe58a1ba1c70d3317.jpg",
                "currency": "RUB",
                "price": 47,
                "discount": 0,
                "discount_price": 47,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 6536,
                "iblock_id": 13,
                "name": "Круассан 4U с кремом ваниль, 50г",
                "infoves": "Вес 1 уп. - 50г",
                "quantity": 13,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/ef4\/10_10_0\/ef400d2e4c9e1b4d3a511fa80ace46a6.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/ef4\/300_300_0\/ef400d2e4c9e1b4d3a511fa80ace46a6.jpg",
                "currency": "RUB",
                "price": 47,
                "discount": 0,
                "discount_price": 47,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 6537,
                "iblock_id": 13,
                "name": "Круассан 4U с клубничным джемом, 50г",
                "infoves": "Вес 1 уп. - 50г",
                "quantity": 2,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/49c\/10_10_0\/49cd79ddf59d956c42ddf38e67335416.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/49c\/300_300_0\/49cd79ddf59d956c42ddf38e67335416.jpg",
                "currency": "RUB",
                "price": 47,
                "discount": 0,
                "discount_price": 47,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 6466,
                "iblock_id": 13,
                "name": "Набор для холодца с говяжьими ногами",
                "infoves": "",
                "quantity": 0,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 770,
                "discount": 0,
                "discount_price": 770,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 6465,
                "iblock_id": 13,
                "name": "Набор для холодца со свиными ногами",
                "infoves": "",
                "quantity": 0,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 700,
                "discount": 0,
                "discount_price": 700,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 4900,
                "iblock_id": 13,
                "name": "Зубная паста R.O.C.S. \"PRO. Деликатное отбеливание. Fresh Mint\", 135г",
                "infoves": "Вес 1 шт. - 135г",
                "quantity": 12,
                "weight": 135,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 423,
                "discount": 0,
                "discount_price": 423,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2343,
                "iblock_id": 13,
                "name": "Полотенца бумажные белые Classic двухслойные Veiro, 2шт.",
                "infoves": "",
                "quantity": 45,
                "weight": 236,
                "pre_picture": "\/upload\/resize_cache\/iblock\/bfc\/10_10_0\/bfc98b0ba8fba843adfb734640f015e1.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/bfc\/300_300_0\/bfc98b0ba8fba843adfb734640f015e1.jpg",
                "currency": "RUB",
                "price": 72,
                "discount": 0,
                "discount_price": 72,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 5651,
                "iblock_id": 13,
                "name": "Масло подсолнечное нерафинированное сыродавленное, Русский Масляник, 500мл",
                "infoves": "Объем 500 мл",
                "quantity": 1,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 365,
                "discount": 0,
                "discount_price": 365,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3984,
                "iblock_id": 13,
                "name": "Горох колотый Мистраль, 900г",
                "infoves": "Вес 1 уп. - 900г",
                "quantity": 11,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/386\/10_10_0\/3861e0a5a54cdccdcb4f4fcb85560784.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/386\/300_300_0\/3861e0a5a54cdccdcb4f4fcb85560784.jpg",
                "currency": "RUB",
                "price": 75,
                "discount": 0,
                "discount_price": 75,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 4822,
                "iblock_id": 13,
                "name": "Оливки зелёные  б\/к сорт Мансанилья, с лимоном, La Explanada, 280г",
                "infoves": "Вес 1 уп. - 280г",
                "quantity": 4,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/a48\/10_10_0\/a4875ee02a4ba7ffefbfcaf4245ed88e.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/a48\/300_300_0\/a4875ee02a4ba7ffefbfcaf4245ed88e.jpg",
                "currency": "RUB",
                "price": 99,
                "discount": 0,
                "discount_price": 99,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 4821,
                "iblock_id": 13,
                "name": "Оливки зеленые б\/к фаршированные шпротами, La Explanada, 280г",
                "infoves": "Вес 1 уп. - 280г",
                "quantity": 31,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 99,
                "discount": 0,
                "discount_price": 99,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3962,
                "iblock_id": 13,
                "name": "Ананасы консервированные кусочки в сиропе, Барко, 580мл",
                "infoves": "Объем 580мл",
                "quantity": 5,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/9a1\/10_10_0\/9a10866831e185deb2bc8871db4d1c85.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/9a1\/300_300_0\/9a10866831e185deb2bc8871db4d1c85.jpg",
                "currency": "RUB",
                "price": 118,
                "discount": 0,
                "discount_price": 118,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3788,
                "iblock_id": 13,
                "name": "Рис длиннозерный пропаренный, 5кг",
                "infoves": "Вес 1 уп. - 5кг",
                "quantity": 3,
                "weight": 5000,
                "pre_picture": "\/upload\/resize_cache\/iblock\/397\/10_10_0\/3974e7856ab1068e5d5551b8b7c66586.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/397\/300_300_0\/3974e7856ab1068e5d5551b8b7c66586.jpg",
                "currency": "RUB",
                "price": 300,
                "discount": 0,
                "discount_price": 300,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2775,
                "iblock_id": 13,
                "name": "Пшено Ярмарка, 800г",
                "infoves": "Вес 1 уп. - 800 г",
                "quantity": 23,
                "weight": 800,
                "pre_picture": "\/upload\/resize_cache\/iblock\/2ee\/10_10_0\/2ee4de085e81951c33cee005041d62f8.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/2ee\/300_300_0\/2ee4de085e81951c33cee005041d62f8.jpg",
                "currency": "RUB",
                "price": 55,
                "discount": 0,
                "discount_price": 55,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2898,
                "iblock_id": 13,
                "name": "Осьминоги молодые в масле Меридиан, 180г",
                "infoves": "В 1 уп. 180г",
                "quantity": 3,
                "weight": 180,
                "pre_picture": "\/upload\/resize_cache\/iblock\/692\/10_10_0\/692dcfb00a4aa674b29d44372d89767c.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/692\/300_300_0\/692dcfb00a4aa674b29d44372d89767c.jpg",
                "currency": "RUB",
                "price": 169,
                "discount": 0,
                "discount_price": 169,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2881,
                "iblock_id": 13,
                "name": "Креветки в рассоле Меридиан, 180г",
                "infoves": "В 1 уп. 180г",
                "quantity": 0,
                "weight": 400,
                "pre_picture": "\/upload\/resize_cache\/iblock\/121\/10_10_0\/1217ee2bac521d96f4769cfdd4e4bfef.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/121\/300_300_0\/1217ee2bac521d96f4769cfdd4e4bfef.jpg",
                "currency": "RUB",
                "price": 149,
                "discount": 0,
                "discount_price": 149,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 4469,
                "iblock_id": 13,
                "name": "Вода кокосовая с манго без сахара Foco, 330мл",
                "infoves": "Объем 330мл",
                "quantity": 48,
                "weight": 330,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 99,
                "discount": 0,
                "discount_price": 99,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2829,
                "iblock_id": 13,
                "name": "Ризотто Yelli с белыми грибами, 250г",
                "infoves": "Вес 1 уп. - 250г",
                "quantity": 14,
                "weight": 250,
                "pre_picture": "\/upload\/resize_cache\/iblock\/983\/10_10_0\/983c18dd65e01a08bd5707dbd2a67f79.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/983\/300_300_0\/983c18dd65e01a08bd5707dbd2a67f79.jpg",
                "currency": "RUB",
                "price": 212,
                "discount": 0,
                "discount_price": 212,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2464,
                "iblock_id": 13,
                "name": "Сок осветленный из груш ФрутоНяНя с 4 мес., 200мл",
                "infoves": "",
                "quantity": 32,
                "weight": 216,
                "pre_picture": "\/upload\/resize_cache\/iblock\/244\/10_10_0\/244483357223930ff14903254d350691.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/244\/300_300_0\/244483357223930ff14903254d350691.jpg",
                "currency": "RUB",
                "price": 25,
                "discount": 0,
                "discount_price": 25,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2435,
                "iblock_id": 13,
                "name": "Подгузники размер XL Merries (12-20 кг), 44 шт.",
                "infoves": "",
                "quantity": 4,
                "weight": 1800,
                "pre_picture": "\/upload\/resize_cache\/iblock\/fb5\/10_10_0\/fb59cee83c686bb67f24c84295095057.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/fb5\/300_300_0\/fb59cee83c686bb67f24c84295095057.jpg",
                "currency": "RUB",
                "price": 1480,
                "discount": 0,
                "discount_price": 1480,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 5383,
                "iblock_id": 13,
                "name": "Наполнитель для кошачьего туалета Зооник, древесный, 5л",
                "infoves": "Объем 5л",
                "quantity": 5,
                "weight": 4000000,
                "pre_picture": "\/upload\/resize_cache\/iblock\/72b\/10_10_0\/72b6e95c27b130617c7c8e0d5a44ff5b.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/72b\/300_300_0\/72b6e95c27b130617c7c8e0d5a44ff5b.jpg",
                "currency": "RUB",
                "price": 99,
                "discount": 0,
                "discount_price": 99,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 2721,
                "iblock_id": 13,
                "name": "Маргарин \"Сливочный Нижегородский\" Хозяюшка, 200г",
                "infoves": "Вес 1 уп. - 200 г",
                "quantity": 5,
                "weight": 200,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 26,
                "discount": 0,
                "discount_price": 26,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 2577,
                "iblock_id": 13,
                "name": "Сельдь филе-кусочки Подкопченная в масле Меридиан, 115г",
                "infoves": "Вес 1 уп. - 115г",
                "quantity": 8,
                "weight": 180,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 88,
                "discount": 0,
                "discount_price": 88,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2864,
                "iblock_id": 13,
                "name": "Суп \"Семь бобов\" Yelli, 250г",
                "infoves": "Вес 1 уп. - 250 г",
                "quantity": 6,
                "weight": 250,
                "pre_picture": "\/upload\/resize_cache\/iblock\/08e\/10_10_0\/08ebc811a0b7cdf339124bc575edc7f6.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/08e\/300_300_0\/08ebc811a0b7cdf339124bc575edc7f6.jpg",
                "currency": "RUB",
                "price": 138,
                "discount": 0,
                "discount_price": 138,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3053,
                "iblock_id": 13,
                "name": "Крахмал картофельный \"Славная Трапеза\", 400г",
                "infoves": "Вес 1 уп. - 400г",
                "quantity": 0,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/29e\/10_10_0\/29e694128a8f668609e1b67a1796136e.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/29e\/300_300_0\/29e694128a8f668609e1b67a1796136e.jpg",
                "currency": "RUB",
                "price": 58,
                "discount": 0,
                "discount_price": 58,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 2358,
                "iblock_id": 13,
                "name": "Туалетная бумага оранжевая Classic Veiro, 2 слоя, 4 рулона",
                "infoves": "",
                "quantity": 11,
                "weight": 224,
                "pre_picture": "\/upload\/resize_cache\/iblock\/05c\/10_10_0\/05c2c799f0a1b40062516ad72db8db50.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/05c\/300_300_0\/05c2c799f0a1b40062516ad72db8db50.jpg",
                "currency": "RUB",
                "price": 48,
                "discount": 0,
                "discount_price": 48,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 4502,
                "iblock_id": 13,
                "name": "Мёд-суфле Кедровый орешек Peroni Honey, 220г",
                "infoves": "Вес 1 шт. - 220г",
                "quantity": 1,
                "weight": 220,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 430,
                "discount": 0,
                "discount_price": 430,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3911,
                "iblock_id": 13,
                "name": "Томаты в собственном соку IJEVAN, 800г",
                "infoves": "Вес 1 шт. - 800г",
                "quantity": 0,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/106\/10_10_0\/106106312c9f832352e50ff645dadefb.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/106\/300_300_0\/106106312c9f832352e50ff645dadefb.jpg",
                "currency": "RUB",
                "price": 209,
                "discount": 0,
                "discount_price": 209,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 2731,
                "iblock_id": 13,
                "name": "Сахар-песок \"Успех Плюс\", 5кг",
                "infoves": "Вес 1 уп. - 5 кг",
                "quantity": 33,
                "weight": 5000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 249,
                "discount": 0,
                "discount_price": 249,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 1658,
                "iblock_id": 13,
                "name": "Зефир \"Белевский\" Клюква в шоколаде, 250г",
                "infoves": "Вес 1 уп. - 250г",
                "quantity": 4,
                "weight": 250,
                "pre_picture": "\/upload\/resize_cache\/iblock\/59f\/10_10_0\/59f32de56992dc6c24eaaecfeb0f0ea4.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/59f\/300_300_0\/59f32de56992dc6c24eaaecfeb0f0ea4.jpg",
                "currency": "RUB",
                "price": 195,
                "discount": 0,
                "discount_price": 195,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 1166,
                "iblock_id": 13,
                "name": "Вода Aqua Minerale без газа, 0,6л",
                "infoves": "Объем 0,6л",
                "quantity": 38,
                "weight": 620,
                "pre_picture": "\/upload\/resize_cache\/iblock\/a98\/10_10_0\/a986317c04ce6b8531958d206890d950.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/a98\/300_300_0\/a986317c04ce6b8531958d206890d950.jpg",
                "currency": "RUB",
                "price": 27,
                "discount": 0,
                "discount_price": 27,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3790,
                "iblock_id": 13,
                "name": "Сахар-песок, 5кг",
                "infoves": "Вес 1 уп. - 5кг",
                "quantity": 9,
                "weight": 5000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 255,
                "discount": 0,
                "discount_price": 255,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3048,
                "iblock_id": 13,
                "name": "Дрожжи \"Саф-Инстант\" сухие, 500г",
                "infoves": "Вес 1 уп. - 500г",
                "quantity": 2,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/e98\/10_10_0\/e980f7f34eaa3a12cf1f2165d321890e.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/e98\/300_300_0\/e980f7f34eaa3a12cf1f2165d321890e.jpg",
                "currency": "RUB",
                "price": 200,
                "discount": 0,
                "discount_price": 200,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 956,
                "iblock_id": 13,
                "name": "Картофель красный мытый",
                "infoves": "На развес",
                "quantity": 44.109,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 78,
                "discount": 0,
                "discount_price": 78,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 2159,
                "iblock_id": 13,
                "name": "Крупа пшеничная \"Кускус\" Мистраль, 450г",
                "infoves": "Вес 1 уп. - 450 г",
                "quantity": 0,
                "weight": 450,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 121,
                "discount": 0,
                "discount_price": 121,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 2103,
                "iblock_id": 13,
                "name": "Ванилин кристаллический, 1,5г",
                "infoves": "Вес 1 пакетика - 1,5 г",
                "quantity": 3,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 10,
                "discount": 0,
                "discount_price": 10,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 3,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2588,
                "iblock_id": 13,
                "name": "Треска свежемороженая, филе, 400г, Agama",
                "infoves": "Вес 1 шт. ~ 0,4 кг",
                "quantity": 11,
                "weight": 400,
                "pre_picture": "\/upload\/resize_cache\/iblock\/74e\/10_10_0\/74e307ab68c41d69016a48c1b40ad9cb.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/74e\/300_300_0\/74e307ab68c41d69016a48c1b40ad9cb.jpg",
                "currency": "RUB",
                "price": 379,
                "discount": 0,
                "discount_price": 379,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3998,
                "iblock_id": 13,
                "name": "Мякоть голени индейки охлажденная, на развес",
                "infoves": "На развес",
                "quantity": 0,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 349,
                "discount": 0,
                "discount_price": 349,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.9,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 3168,
                "iblock_id": 13,
                "name": "Мыло жидкое, 5л",
                "infoves": "Объем 5л",
                "quantity": 4,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 215,
                "discount": 0,
                "discount_price": 215,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 2352,
                "iblock_id": 13,
                "name": "Туалетная бумага белая Deluxe Zewa, 3 слоя, 8 рулонов",
                "infoves": "",
                "quantity": 2,
                "weight": 772,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 198,
                "discount": 0,
                "discount_price": 198,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 3996,
                "iblock_id": 13,
                "name": "Плечевая часть крыла индейки охлажденная, на развес",
                "infoves": "На развес",
                "quantity": 1.64,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 177,
                "discount": 0,
                "discount_price": 177,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.8,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 3997,
                "iblock_id": 13,
                "name": "Голень индейки охлажденная, на развес",
                "infoves": "На развес",
                "quantity": 6.486,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 179,
                "discount": 0,
                "discount_price": 179,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.8,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 978,
                "iblock_id": 13,
                "name": "Лук-резанец (шнитт-лук)",
                "infoves": "На развес",
                "quantity": 0.419,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 1400,
                "discount": 0,
                "discount_price": 1400,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.05,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 5856,
                "iblock_id": 13,
                "name": "Виноград черный с косточками \"Молдова\"",
                "infoves": "На развес",
                "quantity": -0.948,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 135,
                "discount": 0,
                "discount_price": 135,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1440,
                "iblock_id": 13,
                "name": "Печень говяжья замороженая, Мираторг",
                "infoves": "Вес 1 упаковки ~ 1 кг",
                "quantity": 1.898,
                "weight": 1000,
                "pre_picture": "\/upload\/resize_cache\/iblock\/600\/10_10_0\/600022a40a131ba824cb3fc5e5bcbca1.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/600\/300_300_0\/600022a40a131ba824cb3fc5e5bcbca1.jpg",
                "currency": "RUB",
                "price": 299,
                "discount": 0,
                "discount_price": 299,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 4461,
                "iblock_id": 13,
                "name": "Яблоки Симиренко, урожай 2017г.",
                "infoves": "На развес",
                "quantity": 50.099,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 122,
                "discount": 0,
                "discount_price": 122,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 790,
                "iblock_id": 13,
                "name": "Базилик красный",
                "infoves": "На развес",
                "quantity": 0.312,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 1000,
                "discount": 0,
                "discount_price": 1000,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.05,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 795,
                "iblock_id": 13,
                "name": "Лук-порей",
                "infoves": "Вес 1 шт. ~ 450г",
                "quantity": 12.539,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 159,
                "discount": 0,
                "discount_price": 159,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.45,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 912,
                "iblock_id": 13,
                "name": "Петрушка Кудрявая",
                "infoves": "На развес",
                "quantity": 1.254,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 600,
                "discount": 0,
                "discount_price": 600,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.05,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1987,
                "iblock_id": 13,
                "name": "Сельдерей лист",
                "infoves": "На развес",
                "quantity": 12.13,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 450,
                "discount": 0,
                "discount_price": 450,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.2,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 2728,
                "iblock_id": 13,
                "name": "Крем на растительных маслах \"Шантипак\", Puratos, 1л",
                "infoves": "Объем 1 л",
                "quantity": 6,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 155,
                "discount": 0,
                "discount_price": 155,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 798,
                "iblock_id": 13,
                "name": "Розмарин",
                "infoves": "На развес",
                "quantity": 0.446,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 1300,
                "discount": 0,
                "discount_price": 1300,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.05,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 3993,
                "iblock_id": 13,
                "name": "Вырезка свиная охлажденная, на развес",
                "infoves": "На развес",
                "quantity": -0.169,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 369,
                "discount": 0,
                "discount_price": 369,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.55,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 3991,
                "iblock_id": 13,
                "name": "Рулька задняя для запекания охлажденная, на развес",
                "infoves": "На развес",
                "quantity": 4.693,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 199,
                "discount": 0,
                "discount_price": 199,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1.1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1050,
                "iblock_id": 13,
                "name": "Яблоки Гала",
                "infoves": "На развес",
                "quantity": -5.624,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 104,
                "discount": 0,
                "discount_price": 104,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 4025,
                "iblock_id": 13,
                "name": "Апельсины с щербинкой для сока",
                "infoves": "На развес",
                "quantity": 0.324,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 85,
                "discount": 0,
                "discount_price": 85,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2013,
                "iblock_id": 13,
                "name": "Окорочок утиный, без кожи, охлажденный, на развес",
                "infoves": "На развес",
                "quantity": 0.947,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 399,
                "discount": 0,
                "discount_price": 399,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.45,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 2036,
                "iblock_id": 13,
                "name": "Спаржа зеленая, 450г",
                "infoves": "Вес 1 шт. - 450г",
                "quantity": -4,
                "weight": 450,
                "pre_picture": "\/upload\/resize_cache\/iblock\/b59\/10_10_0\/b59656203623c22339f613e47dfa7143.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/b59\/300_300_0\/b59656203623c22339f613e47dfa7143.jpg",
                "currency": "RUB",
                "price": 629,
                "discount": 0,
                "discount_price": 629,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 3992,
                "iblock_id": 13,
                "name": "Мякоть свиного окорока охлажденная, на развес",
                "infoves": "На развес",
                "quantity": 14.201,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 309,
                "discount": 0,
                "discount_price": 309,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1057,
                "iblock_id": 13,
                "name": "Перец чили зеленый Импорт",
                "infoves": "Вес 1 шт. ~ 50г",
                "quantity": 0.092,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 650,
                "discount": 0,
                "discount_price": 650,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.05,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 744,
                "iblock_id": 13,
                "name": "Помело",
                "infoves": "Вес 1 шт. ~ 1,3 - 1,7 кг",
                "quantity": -12.268,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 89,
                "discount": 48.95,
                "discount_price": 40.05,
                "discount_percent": 55,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1990,
                "iblock_id": 13,
                "name": "Горбуша х\/к, без головы, потрошеная",
                "infoves": "На развес",
                "quantity": 2.612,
                "weight": 1000,
                "pre_picture": "\/upload\/resize_cache\/iblock\/556\/10_10_0\/55621aaa731250a58ff59975c4b7baa1.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/556\/300_300_0\/55621aaa731250a58ff59975c4b7baa1.jpg",
                "currency": "RUB",
                "price": 499,
                "discount": 0,
                "discount_price": 499,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.8,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 977,
                "iblock_id": 13,
                "name": "Кукуруза мини, 125г",
                "infoves": "Вес 1 шт. - 125г",
                "quantity": 3,
                "weight": 125,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 119,
                "discount": 0,
                "discount_price": 119,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 2197,
                "iblock_id": 13,
                "name": "Масло оливковое рафинированное Classic Borges, 500мл",
                "infoves": "Объем 500 мл",
                "quantity": 0,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 525,
                "discount": 0,
                "discount_price": 525,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 3028,
                "iblock_id": 13,
                "name": "Язык говяжий замороженный, на развес",
                "infoves": "Вес 1 шт. ~ 1кг",
                "quantity": 15.055,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 475,
                "discount": 0,
                "discount_price": 475,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 735,
                "iblock_id": 13,
                "name": "Груша Конференц",
                "infoves": "На развес",
                "quantity": 85.236,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 144,
                "discount": 0,
                "discount_price": 144,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 2587,
                "iblock_id": 13,
                "name": "Треска свежемороженая, филе-кусок (лойн), 400г, Agama",
                "infoves": "Вес 1 шт. ~ 0,4 кг",
                "quantity": 16,
                "weight": 400,
                "pre_picture": "\/upload\/resize_cache\/iblock\/77e\/10_10_0\/77e6de6f5a6161c1aca1d7b0e8a0905e.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/77e\/300_300_0\/77e6de6f5a6161c1aca1d7b0e8a0905e.jpg",
                "currency": "RUB",
                "price": 468,
                "discount": 0,
                "discount_price": 468,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 1473,
                "iblock_id": 13,
                "name": "Крыло цыпленка-бройлера охлажденное на развес",
                "infoves": "На развес",
                "quantity": -3.294,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 148,
                "discount": 0,
                "discount_price": 148,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1263,
                "iblock_id": 13,
                "name": "Лимонад \"Натахтари\" Крем-сливки, 0,5л",
                "infoves": "Объем 0,5л",
                "quantity": 0,
                "weight": 0,
                "pre_picture": "\/upload\/resize_cache\/iblock\/8a4\/10_10_0\/8a49d85f4820a4b8ec9ac90f8980a428.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/8a4\/300_300_0\/8a49d85f4820a4b8ec9ac90f8980a428.jpg",
                "currency": "RUB",
                "price": 53,
                "discount": 0,
                "discount_price": 53,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 1016,
                "iblock_id": 13,
                "name": "Капуста Савойская",
                "infoves": "На развес",
                "quantity": 17.822,
                "weight": 1000,
                "pre_picture": "\/upload\/resize_cache\/iblock\/c07\/10_10_0\/c078639475837ca0c1b95746cb412c15.jpg",
                "picture": "\/upload\/resize_cache\/iblock\/c07\/300_300_0\/c078639475837ca0c1b95746cb412c15.jpg",
                "currency": "RUB",
                "price": 98,
                "discount": 0,
                "discount_price": 98,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 807,
                "iblock_id": 13,
                "name": "Тархун (эстрагон)",
                "infoves": "На развес",
                "quantity": 0.602,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 1280,
                "discount": 0,
                "discount_price": 1280,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 771,
                "iblock_id": 13,
                "name": "Перец желтый болгарский",
                "infoves": "На развес",
                "quantity": 19.613,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 209,
                "discount": 0,
                "discount_price": 209,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1065,
                "iblock_id": 13,
                "name": "Хурма мелкая \"свечка\"",
                "infoves": "На развес",
                "quantity": -1.263,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 170,
                "discount": 0,
                "discount_price": 170,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": false
            }, {
                "id": 2012,
                "iblock_id": 13,
                "name": "Филе грудки утиное, без кожи, без кости, охлажденное, на развес",
                "infoves": "На развес",
                "quantity": 2.067,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 598,
                "discount": 0,
                "discount_price": 598,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.45,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 772,
                "iblock_id": 13,
                "name": "Перец красный болгарский",
                "infoves": "На развес",
                "quantity": 10.728,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 179,
                "discount": 0,
                "discount_price": 179,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1476,
                "iblock_id": 13,
                "name": "Окорочка куриные охлажденные на развес",
                "infoves": "На развес",
                "quantity": 1.839,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 168,
                "discount": 0,
                "discount_price": 168,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 779,
                "iblock_id": 13,
                "name": "Помидоры черри на ветке, 500г",
                "infoves": "Вес 1 шт. - 500г",
                "quantity": -1,
                "weight": 500,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 245,
                "discount": 0,
                "discount_price": 245,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 899,
                "iblock_id": 13,
                "name": "Виноград красный с косточками",
                "infoves": "На развес",
                "quantity": 33.848,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 178,
                "discount": 0,
                "discount_price": 178,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1053,
                "iblock_id": 13,
                "name": "Картофель белый мытый",
                "infoves": "На развес",
                "quantity": 68.135,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 35,
                "discount": 0,
                "discount_price": 35,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 892,
                "iblock_id": 13,
                "name": "Салат микс, 150г",
                "infoves": "Вес 1 шт. - 150г",
                "quantity": -4,
                "weight": 150,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 135,
                "discount": 0,
                "discount_price": 135,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 3693,
                "iblock_id": 13,
                "name": "Набор суповой рыбный (с головой), замороженный, на развес",
                "infoves": "На развес",
                "quantity": 11.78,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 279,
                "discount": 0,
                "discount_price": 279,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1.2,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 801,
                "iblock_id": 13,
                "name": "Салат Китайский",
                "infoves": "Вес 1 шт. ~ 700г",
                "quantity": 27.054,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 52,
                "discount": 0,
                "discount_price": 52,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.7,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 973,
                "iblock_id": 13,
                "name": "Капуста Кольраби",
                "infoves": "На развес",
                "quantity": 0.52,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 248,
                "discount": 0,
                "discount_price": 248,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 737,
                "iblock_id": 13,
                "name": "Груша Форел",
                "infoves": "На развес",
                "quantity": -16.103,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 286,
                "discount": 0,
                "discount_price": 286,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1992,
                "iblock_id": 13,
                "name": "Филе бедра индейки, без кожи, без кости, охлажденное, на развес",
                "infoves": "На развес",
                "quantity": 2.156,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 369,
                "discount": 0,
                "discount_price": 369,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1911,
                "iblock_id": 13,
                "name": "Сыр \"Пармезан. 3 мес.\" Laime 40%, 200г, кусок",
                "infoves": "Вес 1 шт. - 200г",
                "quantity": 4,
                "weight": 0,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 228,
                "discount": 0,
                "discount_price": 228,
                "discount_percent": 0,
                "measure_id": 5,
                "measure_symbol": "шт",
                "measure_ratio": 1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 745,
                "iblock_id": 13,
                "name": "Яблоки Голден",
                "infoves": "На развес",
                "quantity": 28.228,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 104,
                "discount": 0,
                "discount_price": 104,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }, {
                "id": 2953,
                "iblock_id": 13,
                "name": "Яблоки Черный принц",
                "infoves": "",
                "quantity": 52.248,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 98,
                "discount": 0,
                "discount_price": 98,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1186,
                "iblock_id": 13,
                "name": "Дорадо охлажденная непотрошеная, вес 400-600 г",
                "infoves": "На развес, вес 1 шт. ~ 400-600 г",
                "quantity": 2.894,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 525,
                "discount": 0,
                "discount_price": 525,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.4,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 760,
                "iblock_id": 13,
                "name": "Капуста белокочанная",
                "infoves": "Вес 1 шт. ~ 2 - 3 кг",
                "quantity": 360.092,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 14,
                "discount": 0,
                "discount_price": 14,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 2,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 926,
                "iblock_id": 13,
                "name": "Капуста цветная",
                "infoves": "Вес 1 шт. ~ 1,2кг",
                "quantity": 114.388,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 99,
                "discount": 0,
                "discount_price": 99,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 1.1,
                "traced": false,
                "traced_receipt_in": false,
                "can_by_zero": true,
                "available": true
            }, {
                "id": 1967,
                "iblock_id": 13,
                "name": "Яблоки Роял Гала",
                "infoves": "На развес",
                "quantity": 13.552,
                "weight": 1000,
                "pre_picture": "",
                "picture": "",
                "currency": "RUB",
                "price": 104,
                "discount": 0,
                "discount_price": 104,
                "discount_percent": 0,
                "measure_id": 4,
                "measure_symbol": "кг",
                "measure_ratio": 0.5,
                "traced": true,
                "traced_receipt_in": false,
                "can_by_zero": false,
                "available": true
            }];
        }
    },
    created: function(){        
        this.getGoodList();
    }
    
}
</script>
